language: node_js
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - emerson@emersonveenstra.net
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - http://webhooks.testing2.emersonveenstra.net/webhook
    on_failure: always
    on_success: always
env:
  global:
    - secure: TIAPgvWbYYhM8vsPPCYW4/GIsQHcLIQSSFQZNQp7fzfOrdblktUbyBVw7vGNikI3P9bzTLGjZAv4TTNe64RdA1KbsCPxOU9mMVS50Klj09iSds0nJny1Qy0ssCid0k2YHbflx2XgWclvsV0zsxtN+CYEEFgX/mtyI8rBkyG2nts=
    - secure: LXx8KUE3yQy/xBfE5NkPORCwCLrzz6pElp9R7MjTV1GXvNboiNzyhu5YUTS1SezwVeT0zaVxumWe0sPtM2dxuudPEXct2dP98OSdRNEC1d1tKm4oy5fEGMCS7DBeFt/gXzbfM+/jYehGzlZjsLkqHBXWWbrjlxGxwcckKt2bsfY=
addons:
  sauce_connect: true
  hosts:
    - testing2.emersonveenstra.net
before_install:
  - npm install -g forever
  - npm install -g grunt-cli
before_script:
  - forever start app.js
  - sleep 5
  - forever logs 0
  - ping -c 1 testing2.emersonveenstra.net
  - curl localhost:5672
after_success:
  - forever stopall
after_failure:
  - curl localhost:5672
  - forever logs 0