language: node_js
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - emerson@emersonveenstra.net
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - http://webhooks.testing2.emersonveenstra.net/webhook
    on_failure: always
    on_success: always
env:
  global:
    - secure: RUlUMo595afma7TinBWQrT0lwN/WRN8+BbMik2UGJzi9sO7hqpau7Qbw9twsY/S9GNuMc8nJ+Mosg6j4Pxh/C4KLnYTG8H4vuwKkbNnGp6l2jJAkrmPk8a2VtRFoZnz2x0ZectETjzljnKmHdaX6TxvHY7SaFVOYaCiLFIeDbFQ=
    - secure: V3r4lh9I6jFWLep0J5I02zpjGda5JgH6tOFEuCG2O3bjmVMaOyzx2upy5gErYMpQ0lCEILJM20g89PQqLIQTh/LpsO7HW3xGL85oYYU1ySpdNuUtIMNiX49PnJ7sLk3etUmBBRqb8b8mPANJBkjoKd6nQUH8NNF39F5Z5FUw3B4=
addons:
  sauce_connect: true
  hosts:
    - testing2.emersonveenstra.net
before_install:
  - npm install -g forever
  - npm install -g grunt-cli
before_script:
  - forever start app.js
  - sleep 5
  - forever logs 0
  - ping -c 1 testing2.emersonveenstra.net
  - curl localhost:5672
after_success:
  - forever stopall
after_failure:
  - curl localhost:5672
  - forever logs 0
