language: node_js
node_js:
  - "0.10"
notifications:
  webhooks:
    urls:
      - http://webhooks.testing2.emersonveenstra.net/webhook
    on_failure: always
    on_success: always
env:
  global:
    - SAUCE_USERNAME=codevine
    - SAUCE_ACCESS_KEY=6145a59e-8d0e-45d3-94ff-dec50b4085a3
before_install:
  - curl https://gist.githubusercontent.com/emersonveenstra/65e92a0726fd63821447/raw/2c4c545bd6a6cfb47b8726e451d52ed8ba6502aa/sauce-connect.sh | bash
  - npm install -g forever
  - npm install -g grunt-cli
before_script:
  - forever start app.js
  - sleep 5
  - forever logs 0
after_success:
  - forever stopall
after_failure:
  - forever logs 0
